---
# handlers file for wp-nginx
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: Restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted