#---
#- name: Configure storage-iscsi nodes
#  hosts: storage
#  gather_facts: yes
#  become: true
#  roles:
#    - role: storage-iscsi
#      vars:
#        storage_interface: 'eth1'
#        iqn_domain: "{{ ansible_hostname }}"
#        iscsi_object: iqn.2021-03
#        block_device: '/dev/sdb'
#
#- name: Configure gfs2 nodes
#  hosts: gfs_nodes
#  gather_facts: yes
#  become: true
#  roles:
#    - role: gfs2
#      vars:
#        pacemaker_name: 'hacluster'
#        pacemaker_user: 'hacluster'
#        pacemaker_password: 'hacluster'
#        storage_interface: 'eth1'
#        iscsi_portal_ip: "{{ hostvars[groups['storage'][0]]['ansible_' + storage_interface].ipv4.address }}"
#        cluster_vg: "cluster_vg"
#        cluster_lv: "cluster_lv"
#        mount_to: "/mnt"
#

- name: Configure nginx nodes
  hosts: nginx_nodes
  gather_facts: yes
  become: true
  roles:
    - role: hostname-builder
      vars:
        interface: "{{ web_net_iface }}"
    - role: nginx-phpfpm
      vars:
        nginx_bind_port: 8080
        nginx_bind_iface: "{{ web_net_iface }}"

        
    #- role: sedovandrew.nginx
    #nginx_http_default_server_port: 8080
    #- role: nginxinc.nginx_config
