---
- name: Configure db node
  hosts: db
  gather_facts: yes
  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_enabled_on_startup: true
        mysql_bind_address: "{{hostvars[inventory_hostname]['ansible_' + db_net_iface].ipv4.address }}"
        
- name: Configure nginx nodes
  hosts: nginx_nodes
  gather_facts: yes
  become: true
  roles:
    - role: hostname-builder
      vars:
        interface: "{{ web_net_iface }}"
    - role: nginx-phpfpm
      vars:
        nginx_bind_port: 8080
        nginx_bind_iface: "{{ web_net_iface }}"
