---
- name: Configure hostnames for nginx_nodes
  become: true
  hosts: nginx_nodes, db
  roles:
    - role: hostname-builder
      vars:
        interface: "{{ db_net_iface }}"

- name: Configure db node
  hosts: db
  gather_facts: yes
  become: true
  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_bind_address: "{{hostvars[inventory_hostname]['ansible_' + db_net_iface].ipv4.address }}"
        mysql_enabled_on_startup: true
        mysql_root_password_update: true
        mysql_user_password_update: true
        mysql_skip_name_resolve: true
        mysql_databases:
          - name: "{{ wp_db }}"
        mysql_users:
          - name: "{{ wp_user }}"
            host: "%"
            password: "{{ wp_password }}"
            priv: "{{ wp_db + '.*:ALL'}}"

- name: Configure nginx nodes
  hosts: nginx_nodes
  gather_facts: yes
  become: true
  roles:
    - role: nginx-phpfpm
      vars:
        nginx_bind_port: 8080
        nginx_bind_iface: "{{ web_net_iface }}"

- name: Configure wp nodes
  hosts: nginx_nodes
  gather_facts: yes
  become: true
  roles:
    - role: wp-nginx
