---
# config file for storage-iscsi

- name: Enable target service
  systemd:
    name: target
    state: started
    enabled: yes

- name: Check if backstore already exists
  command: targetcli /backstores/block/{{ disk_name }} status
  register: backstore_status
  failed_when: backstore_status.rc > 0 and "No such path" not in backstore_status.stderr

- name: Disable portal creation by default
  command: targetcli set global auto_add_default_portal=false

- name: Create a new backstore
  command: targetcli backstores/block create {{ disk_name }} {{ block_device }}
  when: '"No such path" in backstore_status.stderr'
  register: backstore_create

- name: Create iscsi object
  command: targetcli iscsi/ create {{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}
  when: backstore_create.changed
  register: iscsi_object_created

- name: Set attribute demo_mode_write_protect=0
  command: targetcli iscsi/{{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}/tpg1/ set attribute demo_mode_write_protect=0
  when: iscsi_object_created.changed

- name: Enable acl auto generation
  command: targetcli iscsi/{{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}/tpg1/ set attribute authentication=0
  when: iscsi_object_created.changed

- name: Enable acl auto generation
  command: targetcli iscsi/{{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}/tpg1/ set attribute generate_node_acls=1
  when: iscsi_object_created.changed

- name: Create portal for iscsi object
  command: targetcli iscsi/{{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}/tpg1/portals/ create {{ hostvars[inventory_hostname]['ansible_' + storage_interface].ipv4.address }}
  when: iscsi_object_created.changed
  register: portal_iscsi_object

- name: Add lun to iscsi object
  command: targetcli iscsi/{{ iscsi_object }}.{{ iqn_domain }}.local:{{ disk_name }}/tpg1/luns/ create /backstores/block/{{ disk_name }}
  when: portal_iscsi_object.changed
  register: lun_to_iscsi_object

- name: Save targetcli changes
  command: targetcli saveconfig
  when: lun_to_iscsi_object.changed
  register: save_targetcli_config
  