
---
- name: Install NGINX
  hosts: all
  become: true
  tasks:
  - name: Update yum cache
    yum:  update_cache=yes

  - name: Install epel release
    yum:
      name:  epel-release
      state: present

  - name: Install NGINX web server
    yum:
      name: nginx
      state: present

  - name: Make sure that the NGINX service is running
    ansible.builtin.systemd:
      state: started
      name: nginx