---
- name: Check os version
  fail: msg='OS is NOT CentOS 8.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '8'

#- name: Upgrade all packages
#  dnf: name=* state=latest
  
- name: Install packages
  dnf:
    name:
      - php
      - curl
      - wget
      - php-mysqlnd 
      - php-opcache 
      - php-gd 
      - php-xml 
      - php-mbstring
      - php-json
