---
#
# Disable SELinux
- selinux:
    state: disabled

- name: Download wp
  get_url:
    url: "https://wordpress.org/{{ wp_version }}.tar.gz"
    dest: "/tmp/{{ wp_version }}.tar.gz"
    force: no

- name: Ensure {{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }} directory exists
  file:
    path: "{{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }}"
    state: directory

- name: Unarchive wp
  unarchive:
    src: "/tmp/{{ wp_version }}.tar.gz"
    dest: "{{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Deploy NGINX config from template
  template:
    src: "{{ wp_nginx_conf + '.conf.j2' }}"
    dest: "{{ nginx_conf_dir + wp_nginx_conf + '.conf'}}"
    mode: 0755

- name: Deploy wp php-fpm pool from template
  template:
    src: "{{ wp_fpm_pool_name + '.conf.j2' }}"
    dest: "{{ fpm_pools_conf_path + wp_fpm_pool_name + '.conf'}}"
    mode: 0755

- name: Fetch random salts for WordPress config
  shell: curl -s https://api.wordpress.org/secret-key/1.1/salt/
  register: shell_output

- set_fact:
    wp_salt : "{{ shell_output.stdout }}"

- name: Deploy wp config from template
  template:
    src: "{{ wp_conf + '.j2' }}"
    dest: "{{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }}/{{ wp_conf }}"
    mode: 0755
