---
#
# Disable SELinux
- selinux:
    state: disabled

- name: Download wp
  get_url:
    url: "https://wordpress.org/{{ wp_version }}.tar.gz"
    dest: "/tmp/{{ wp_version }}.tar.gz"
    force: no

- name: Ensure {{ nginx_html_root_dir }}{{ wp_dir_prefix }}-{{ wp_version }} directory exists
  file:
    path: "{{ nginx_html_root_dir }}{{ wp_dir_prefix }}-{{ wp_version }}"
    state: directory

- name: Unarchive wp
  unarchive:
    src: "/tmp/{{ wp_version }}.tar.gz"
    dest: "{{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Deploy NGINX config from template
  template:
    src: "{{ wp_nginx_conf + '.conf.j2' }}"
    dest: "{{ nginx_conf_dir + wp_nginx_conf + '.conf'}}"
    mode: 0755

- name: Deploy wp php-fpm pool from template
  template:
    src: "{{ wp_fpm_pool_name + '.conf.j2' }}"
    dest: "{{ fpm_pools_conf_path + wp_fpm_pool_name + '.conf'}}"
    mode: 0755

- name: Fetch random salts for WordPress config
  shell: curl -s https://api.wordpress.org/secret-key/1.1/salt/
  register: shell_output

- set_fact:
    wp_salt : "{{ shell_output.stdout }}"

- name: Deploy wp config from template
  template:
    src: "{{ wp_conf + '.j2' }}"
    dest: "{{ nginx_html_root_dir }}/{{ wp_dir_prefix }}-{{ wp_version }}/{{ wp_conf }}"
    mode: 0755
  
- name: reload service nginx
  systemd:
    name: nginx
    state: reloaded  

- name: reload service php-fpm
  systemd:
    name: php-fpm
    state: reloaded  

- name: Download wp-cli
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/tmp/wp-cli.phar"
    force: no

- name: Move wp-cli
  ansible.builtin.copy:
    src: /tmp/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

- name: Generate wp admin password if empty
  set_fact:
     wp_admin_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits') }}"
  when: wp_admin_password | length == 0

- name: Setup wp
  command: /usr/local/bin/wp core install --path={{ nginx_html_root_dir }}{{ wp_dir_prefix }}-{{ wp_version }} --url={{ wp_url }} --title={{ wp_title }} --admin_name={{ wp_admin }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }}
